### ISSUE TITLE
Answers reading problem

### ISSUE THREAD

**Issue by mayamolodec** [snad-space/zwad#105]
Mistake was found. Presumably in this 254b586367da5b4d40f6309425316f6f84214d4f git log.
Now answers are recording with a space between "oid" and "is_anomaly", and between columns too. This caused the problem with answers reading. If all the spaces deleted - everything works correctly.

**Comment by matwey** [comment]
What was the initial issue?

**Comment by hombit** [comment]
As far as I understand the issue comes from the change of the answer file format introduced in https://github.com/snad-space/zwad/commit/254b586367da5b4d40f6309425316f6f84214d4f. There CSV header changed from `oid,is_anomaly` to `oid, is_anomaly`, note that an extra space appeared between `is_anomaly`. This changes pandas column name to ` is_anomaly` (with space) and brakes the code loading previous answers

**Comment by matwey** [comment]
Why don't use `skipinitialspace=True` in `pandas.read_csv`?
