### ISSUE TITLE
save AAD model in before final analysis

### ISSUE THREAD

**Issue by emilleishida** [snad-space/zwad#74]
It would be nice to allow the AAD model to be saved after a few replies from the expert. 

If the model is saved locally, the expert can continue the analysis some other time by loading the saved model.
This would also enable parallel analysis using multiple definitions of anomaly.

**Comment by hombit** [comment]
Related to #89

**Comment by hombit** [comment]
It is probably not so related to #89, because here we talk about reusing of the initial random forest model to speed-up initial wait time before an expert start to answer to AAD, while in #89 we talk about saving the final expert-trained model.

I think that we can close this issue since `zwaad` is reimplemented via `coniferest` (PR #119) and initial model is trained much-much faster now.
